apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ws-oneplatform-equipment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: ws-oneplatform-equipment
    spec:
      containers:
        - name: ws-oneplatform-equipment
          image: 'gcr.io/$GOOGLE_CLOUD_PROJECT/ws-oneplatform-equipment:v1'
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ws-oneplatform-equipment-service
  labels:
    name: ws-oneplatform-equipment-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: ws-oneplatform-equipment
  type: LoadBalancer
